site_name: Alexandria - scRNA Data Library
repo_url: https://github.com/ShalekLab/alexandria
site_author: Shalek Lab
nav:
  - 'Introduction': 'index.md'
  - 'The Alexandria Metadata Convention' : 'metadata.md'
  - 'dropseq_cumulus on Alexandria': 'alexandria.md'
  - 'dropseq_cumulus on Terra': 'terra.md'
  - 'dropseq_cumulus Inputs/Outputs': 'dropseq_cumulus.md'
  - 'Alternatives For Uploading Data' : 'dataupload.md'
theme: readthedocs