site_name: Alexandria - scRNA Data Library
repo_url: https://github.com/ShalekLab/alexandria
site_author: Shalek Lab
nav:
  - 'Introduction': 'index.md'
theme: readthedocs
site_dir: '/home/docs/checkouts/readthedocs.org/user_builds/alexandria-scrna-data-library/checkouts/html/'