FROM mitlovelab/seqwelltcranalysis:v1.0

COPY FASTQtoBAM.sh /TCRAnalysis/bin/FASTQtoBAM.sh
COPY CynoTCRv4/CynoTCRv4.fa /TCRAnalysis/bin/CynoTCRv3.fa
COPY CynoTCRv4/CynoTCRv4.fa.nhr /TCRAnalysis/bin/CynoTCRv3.fa.nhr
COPY CynoTCRv4/CynoTCRv4.fa.nin /TCRAnalysis/bin/CynoTCRv3.fa.nin
COPY CynoTCRv4/CynoTCRv4.fa.nog /TCRAnalysis/bin/CynoTCRv3.fa.nog
COPY CynoTCRv4/CynoTCRv4.fa.nsd /TCRAnalysis/bin/CynoTCRv3.fa.nsd
COPY CynoTCRv4/CynoTCRv4.fa.nsi /TCRAnalysis/bin/CynoTCRv3.fa.nsi
COPY CynoTCRv4/CynoTCRv4.fa.nsq /TCRAnalysis/bin/CynoTCRv3.fa.nsq