FROM mitlovelab/seqwelltcranalysis:v1.0

COPY FASTQtoBAM.sh /TCRAnalysis/bin/FASTQtoBAM.sh
COPY CynoTCRv4/macFasCDR3bases_v4.txt /TCRAnalysis/bin/macFasCDR3bases_v3.txt
COPY CynoTCRv4/CynoTCRv4.fa /TCRAnalysis/bin/CynoTCRv3.fa
COPY CynoTCRv4/CynoTCRv4.fa.nhr /TCRAnalysis/bin/CynoTCRv3.fa.nhr
COPY CynoTCRv4/CynoTCRv4.fa.nin /TCRAnalysis/bin/CynoTCRv3.fa.nin
COPY CynoTCRv4/CynoTCRv4.fa.nog /TCRAnalysis/bin/CynoTCRv3.fa.nog
COPY CynoTCRv4/CynoTCRv4.fa.nsd /TCRAnalysis/bin/CynoTCRv3.fa.nsd
COPY CynoTCRv4/CynoTCRv4.fa.nsi /TCRAnalysis/bin/CynoTCRv3.fa.nsi
COPY CynoTCRv4/CynoTCRv4.fa.nsq /TCRAnalysis/bin/CynoTCRv3.fa.nsq
COPY CynoTCRv4/CynoTCRv4.fa.amb /TCRAnalysis/bin/CynoTCRv3.fa.amb
COPY CynoTCRv4/CynoTCRv4.fa.ann /TCRAnalysis/bin/CynoTCRv3.fa.ann
COPY CynoTCRv4/CynoTCRv4.fa.bwt /TCRAnalysis/bin/CynoTCRv3.fa.bwt
COPY CynoTCRv4/CynoTCRv4.fa.ndb /TCRAnalysis/bin/CynoTCRv3.fa.ndb
COPY CynoTCRv4/CynoTCRv4.fa.not /TCRAnalysis/bin/CynoTCRv3.fa.not
COPY CynoTCRv4/CynoTCRv4.fa.ntf /TCRAnalysis/bin/CynoTCRv3.fa.ntf
COPY CynoTCRv4/CynoTCRv4.fa.nto /TCRAnalysis/bin/CynoTCRv3.fa.nto
COPY CynoTCRv4/CynoTCRv4.fa.pac /TCRAnalysis/bin/CynoTCRv3.fa.pac
COPY CynoTCRv4/CynoTCRv4.fa.sa /TCRAnalysis/bin/CynoTCRv3.fa.sa