---
title: "Seurat to SCP Outputs Notebook"
---

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.
When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Cmd+Shift+K* to preview the HTML file).

# RUN EVERYTHING IN ONE GO
## 1. Load Seurat Object(s)
```{r}
library(Seurat)

# Removes all data values from Global Environment to make as much room as possible.
rm(list = ls())

# Edit this
output.dir <- ''

output.prefix <- paste(output.dir, "SCP", sep='')

# Paths to .Rds/.Rdata seurat objects. 
# Paste path names in quotation marks on each line and delimit with ',' and a newline.
seurat.paths <- c(
                  #"/Users/jggatter/Desktop/Alexandria/alexandria_repository/uploadHelpers/allergen.RData",
                  #"/Users/jggatter/Desktop/Alexandria/alexandria_repository/uploadHelpers/Split_Up/B_comb.RData"
                  #"/Users/jggatter/Desktop/Alexandria/alexandria_repository/uploadHelpers/Split_Up/CD4_comb.RData"
                  #"/Users/jggatter/Desktop/Alexandria/alexandria_repository/uploadHelpers/Objects/Week13.All.Seurat.Rdata",
                  "/Users/jggatter/Desktop/Alexandria/alexandria_repository/uploadHelpers/Objects/Week25.All.Seurat.Rdata"
                )
if (length(seurat.paths) == 0) stop("No paths were entered.")
```

## 2. Everything in one go
```{r}
# A dataframe that will be composed of Path, Name, Expression Matrix, 
df <- data.frame()
for (path in seurat.paths){
  row <- data.frame(Path=path)
  row$Name <- load(path)
  row$OriginalVersion <- get(row$Name)@version
  
  # Update the Seurat Object to the newest version
  object = UpdateSeuratObject(get(row$Name))
  
  # De-allocate the old Seurat object to save space
  rm(list=c(row$Name))
  
  # TODO: tweak this to prefix cells before merging
  # https://www.rdocumentation.org/packages/Seurat/versions/3.1.1/topics/RenameCells
  RenameCells(object, add.cell.id = row$Name) #for.merge = True, ...
  
  expr.data = object@assays$RNA@data
  #expr.filename <- paste(output.prefix, "_norm_expression.txt.gz", sep='')
  expr.filename <- paste(output.prefix, "_norm_expression.txt", sep='')
  source("scp_save_seurat.R")
  expr.df <- add_gene_column(expr.data, row$Name) 
  print("Writing dense matrix as .txt.gz, this step could take up to 30 minutes depending on the size of the object.")
  #write.csv.gz(x=expr.df, file=expr.filename, quote=FALSE, sep='\t', col.names=TRUE)
  fwrite(x=expr.df, file=expr.filename, quote=FALSE, sep='\t', col.names=TRUE)
  gzip(expr.filename, destname=paste(expr.filename, ".gz", sep=''))
  
  dim.red.df <- object@meta.data
  # USER INPUT: change these if the column names of your dimensionality reduction are not the ones used below
  X.name <- "X_umap1"
  Y.name <- "X_umap2"
  # USER INPUT: change this to reflect the name of your dimensionality reduction type
  cluster_file_prefix <- paste(output.prefix, row$Name, "umap", sep='_')
  save_cluster_file(dim.red.df, X.name, Y.name, row$Name, row$Name)
  
  merged.metadata.df = data.frame()
  metadata.df <- data.frame(CELLS=paste(row$Name, rownames(object@meta.data), sep='_'), seurat.metadata)
  merged.metadata.df = merge(merged.metadata.df, metadata.df)
  
  # Add the row to the dataframe
  df <- rbind(df, row)
  #De-allocate the updated Seurat object to save space
  rm(object)
}
View(df)
```
# Testing one object at a time
```{r}
library(Seurat)
output.dir <- ''
output.prefix <- paste(output.dir, "SCP", sep='')

# Paths to .Rds/.Rdata seurat objects. 
# Paste path names in quotation marks on each line and delimit with ',' and a newline.
seurat.paths <- c(
                  #"/Users/jggatter/Desktop/Alexandria/alexandria_repository/uploadHelpers/allergen.RData",
                  "/Users/jggatter/Desktop/Alexandria/alexandria_repository/uploadHelpers/Split_Up/B_comb.RData",
                  "/Users/jggatter/Desktop/Alexandria/alexandria_repository/uploadHelpers/Split_Up/CD4_comb.RData"
                  #"/Users/jggatter/Desktop/Alexandria/alexandria_repository/uploadHelpers/Objects/Week13.All.Seurat.Rdata",
                  #"/Users/jggatter/Desktop/Alexandria/alexandria_repository/uploadHelpers/Objects/Week25.All.Seurat.Rdata"
                )
if (length(seurat.paths) == 0) stop("No paths were entered.")
```

```{r}
df <- data.frame()

  row <- data.frame(Path=path)
  row$Name <- load(path)
  row$OriginalVersion <- get(row$Name)@version
  
  # Update the Seurat Object to the newest version
  object = UpdateSeuratObject(get(row$Name))
  row$UpdatedVersion <- load(object)
  
  # De-allocate the old Seurat object to save space
  #rm(list=c(row$Name))
  
  # TODO: tweak this to prefix cells before merging
  # https://www.rdocumentation.org/packages/Seurat/versions/3.1.1/topics/RenameCells
  RenameCells(object, add.cell.id = row$Name) #for.merge = True, ...
```

```{r}
  library(data.table)
  library(R.utils)
  expr.data = object@assays$RNA@data
  expr.filename <- paste(output.prefix, "_norm_expression.txt", sep='')
  source("scp_save_seurat.R")
  expr.df <- add_gene_column(expr.data, row$Name) 
  print("Writing expression matrix")
  #write.csv.gz(x=expr.df, file=expr.filename, quote=FALSE, sep='\t', col.names=TRUE)
  fwrite(x=expr.df, file=expr.filename, quote=FALSE, sep='\t', col.names=TRUE)
  print("Compressing expression matrix to .txt.gz file.")
  gzip(expr.filename, destname=paste(expr.filename, ".gz", sep=''))
```

```{r}
  dim.red.df <- object@meta.data
  # USER INPUT: change these if the column names of your dimensionality reduction are not the ones used below
  X.name <- "X_umap1"
  Y.name <- "X_umap2"
  # USER INPUT: change this to reflect the name of your dimensionality reduction type
  cluster_file_prefix <- paste(output.prefix, row$Name, "umap", sep='_')
  save_cluster_file(dim.red.df, X.name, Y.name, row$Name, row$Name)
```

```{r}
library(Seurat)

metadata.dfs = vector("list", length = 2)
i<-1

for (path in seurat.paths){
  object.name = load(path)
  object = UpdateSeuratObject(get(object.name))
  rm(get(object.name))

  
  
}
```

```{r}
#metadata.dfs = vector("list", length = length(seurat.paths))

```

```{r}
seurat.paths <- c(
                  #"/Users/jggatter/Desktop/Alexandria/alexandria_repository/uploadHelpers/allergen.RData",
                  "/Users/jggatter/Desktop/Alexandria/alexandria_repository/uploadHelpers/Split_Up/B_comb.RData",
                  "/Users/jggatter/Desktop/Alexandria/alexandria_repository/uploadHelpers/Split_Up/CD4_comb.RData"
                  #"/Users/jggatter/Desktop/Alexandria/alexandria_repository/uploadHelpers/Objects/Week13.All.Seurat.Rdata",
                  #"/Users/jggatter/Desktop/Alexandria/alexandria_repository/uploadHelpers/Objects/Week25.All.Seurat.Rdata"
                )

#metadata.dfs = vector("list", length = 2)
metadata.dfs = list()
i<-1

for (i in seq(from=1, to=length(seurat.paths), by=1)){
  object.name <- load(seurat.paths[i])
  object = UpdateSeuratObject(get(object.name))
  rm(list=c(object.name))
  
  metadata.df = data.frame(CELLS=paste(object.name, rownames(object@meta.data), sep='_'), object@meta.data)
  #append(x=metadata.dfs, values=metadata.df, after=0)
  metadata.dfs[[i]] <- metadata.df
  #print(head(metadata.dfs[i]))
  rm(metadata.df)
}
print("done")
```

```{r}
merged.metadata.df = Reduce(function(x, y) merge(x, y, all=TRUE), metadata.dfs)
write.table("merged_metadata.txt", quote=FALSE, sep='\t', x=merged.metadata.df, row.names=FALSE)
```

